trigger:
- main

pool:
  name: 'self-hosted'

stages:
  - stage: buildimage
    displayName: Build image
    jobs:
      - job: buildimage
        displayName: Build image
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'docker'
              repository: 'myew09.azurecr.io/myapp'
              command: 'build'
              Dockerfile: 'Dockerfile'
              tags: 'latest'
