trigger:
- main

pool: Default
  


stages:
  - stage: buildimage
    displayName: Build image
    jobs:
      - job: buildimage
        displayName: Build image
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'docker'
            repository: 'myew09.azurecr.io'
            command: 'build'
            Dockerfile: '.'
       